# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\x12\x02pd\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n\x0bTemperature\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07station\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\" \n\x08\x41\x64\x64Reply\x12\x14\n\x0crecord_count\x18\x01 \x01(\x04\x32<\n\x07Weather\x12\x31\n\x0e\x41\x64\x64Temperature\x12\x0f.pd.Temperature\x1a\x0c.pd.AddReply\"\x00\x62\x06proto3')



_TEMPERATURE = DESCRIPTOR.message_types_by_name['Temperature']
_ADDREPLY = DESCRIPTOR.message_types_by_name['AddReply']
Temperature = _reflection.GeneratedProtocolMessageType('Temperature', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATURE,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:pd.Temperature)
  })
_sym_db.RegisterMessage(Temperature)

AddReply = _reflection.GeneratedProtocolMessageType('AddReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDREPLY,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:pd.AddReply)
  })
_sym_db.RegisterMessage(AddReply)

_WEATHER = DESCRIPTOR.services_by_name['Weather']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEMPERATURE._serialized_start=54
  _TEMPERATURE._serialized_end=141
  _ADDREPLY._serialized_start=143
  _ADDREPLY._serialized_end=175
  _WEATHER._serialized_start=177
  _WEATHER._serialized_end=237
# @@protoc_insertion_point(module_scope)
